/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author agungrb
 */
public class LihatDataMahasiswa extends javax.swing.JFrame implements View {

    /**
     * Creates new form LihatDataMahasiswa
     */
    public LihatDataMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        txFieldPemb2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txFieldNSKS = new javax.swing.JTextField();
        txFieldStatus = new javax.swing.JTextField();
        txFieldNama = new javax.swing.JTextField();
        txFieldId = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txFieldNIM = new javax.swing.JTextField();
        txFieldJudulTA = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txFieldPemb1 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lihat Data Mahasiswa");

        jLabel24.setText("Jumlah SKS");

        jLabel28.setText("Pembimbing 1");

        jLabel25.setText("Status KP");

        jLabel29.setText("Pembimbing 2");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        txFieldPemb2.setEditable(false);
        txFieldPemb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldPemb2ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("LIHAT DATA MAHASISWA");

        txFieldNSKS.setEditable(false);
        txFieldNSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNSKSActionPerformed(evt);
            }
        });

        txFieldStatus.setEditable(false);
        txFieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldStatusActionPerformed(evt);
            }
        });

        txFieldNama.setEditable(false);
        txFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNamaActionPerformed(evt);
            }
        });

        txFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldIdActionPerformed(evt);
            }
        });

        jLabel27.setText("Nama");

        txFieldNIM.setEditable(false);
        txFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNIMActionPerformed(evt);
            }
        });

        txFieldJudulTA.setEditable(false);
        txFieldJudulTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldJudulTAActionPerformed(evt);
            }
        });

        jLabel17.setText("ID Mahasiswa");

        jLabel3.setText("Judul TA");

        jLabel23.setText("NIM");

        txFieldPemb1.setEditable(false);
        txFieldPemb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldPemb1ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addGap(110, 110, 110)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txFieldNama, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txFieldNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txFieldNSKS, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txFieldStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txFieldJudulTA)
                                    .addComponent(txFieldPemb1)
                                    .addComponent(txFieldPemb2))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txFieldNSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldJudulTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldPemb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldPemb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnOK)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOKActionPerformed

    private void txFieldPemb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldPemb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldPemb2ActionPerformed

    private void txFieldNSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNSKSActionPerformed

    private void txFieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldStatusActionPerformed

    private void txFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNamaActionPerformed

    private void txFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldIdActionPerformed

    private void txFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNIMActionPerformed

    private void txFieldJudulTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldJudulTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldJudulTAActionPerformed

    private void txFieldPemb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldPemb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldPemb1ActionPerformed

    public JButton getBtnOK() {
        return btnOK;
    }

    public JButton getBtnBack() {
        return btnBack;
    }
    

    public void setTxFieldNSKS(int jumlahSKS) {
        txFieldNSKS.setText(Integer.toString(jumlahSKS));
    }
    public void setTxFieldNIM(long nim) {
        txFieldNIM.setText(Long.toString(nim));
    }
    public void setTxFieldNama(String nama) {
        txFieldNama.setText(nama);
    }
    public void setTxFieldStatus(boolean statusKP) {
        if(statusKP) {
            txFieldStatus.setText("Sudah");
        }
        else {
            txFieldStatus.setText("Belum");    
        }
    }
    

    public void setTxFieldJudulTA(String s) {
        txFieldJudulTA.setText(s);
    }
    public void setTxFieldPemb1(String s) {
        this.txFieldPemb1.setText(s);
    }
    public void setTxFieldPemb2(String s) {
        this.txFieldPemb2.setText(s);
    }
    
    public int getTxFieldId() {
        return Integer.parseInt(txFieldId.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txFieldId;
    private javax.swing.JTextField txFieldJudulTA;
    private javax.swing.JTextField txFieldNIM;
    private javax.swing.JTextField txFieldNSKS;
    private javax.swing.JTextField txFieldNama;
    private javax.swing.JTextField txFieldPemb1;
    private javax.swing.JTextField txFieldPemb2;
    private javax.swing.JTextField txFieldStatus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnOK.addActionListener(e);
        btnBack.addActionListener(e);
    }
}
