/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author agungrb
 */
public class OlahDataDosen extends javax.swing.JFrame implements View {

    /**
     * Creates new form OlahDataDosen
     */
    public OlahDataDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRmKelompokTA = new javax.swing.JButton();
        btnAddAnggota = new javax.swing.JButton();
        btnRmAnggota = new javax.swing.JButton();
        btnReplacePembimbing = new javax.swing.JButton();
        txFieldNama = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btnAddKelompokTA = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olah Data Dosen");

        btnRmKelompokTA.setText("Remove Kelompok TA");
        btnRmKelompokTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmKelompokTAActionPerformed(evt);
            }
        });

        btnAddAnggota.setText("Add Anggota");
        btnAddAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnggotaActionPerformed(evt);
            }
        });

        btnRmAnggota.setText("Remove Anggota");

        btnReplacePembimbing.setText("Ganti Pembimbing");
        btnReplacePembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplacePembimbingActionPerformed(evt);
            }
        });

        txFieldNama.setEditable(false);
        txFieldNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txFieldNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFieldNama.setBorder(null);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("OLAH DATA DOSEN");

        btnAddKelompokTA.setText("Add Kelompok TA");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txFieldNama)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRmKelompokTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddKelompokTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRmAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReplacePembimbing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(3, 3, 3)
                .addComponent(txFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddKelompokTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRmKelompokTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRmAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReplacePembimbing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRmKelompokTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmKelompokTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRmKelompokTAActionPerformed

    private void btnAddAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAnggotaActionPerformed

    private void btnReplacePembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplacePembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReplacePembimbingActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnAddAnggota() {
        return btnAddAnggota;
    }

    public JButton getBtnAddKelompokTA() {
        return btnAddKelompokTA;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnReplacePembimbing() {
        return btnReplacePembimbing;
    }

    public JButton getBtnRmAnggota() {
        return btnRmAnggota;
    }

    public JButton getBtnRmKelompokTA() {
        return btnRmKelompokTA;
    }
    
    public void setTxFieldNama(String s) {
        txFieldNama.setText("Hai, "+s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnggota;
    private javax.swing.JButton btnAddKelompokTA;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReplacePembimbing;
    private javax.swing.JButton btnRmAnggota;
    private javax.swing.JButton btnRmKelompokTA;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JTextField txFieldNama;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnAddAnggota.addActionListener(e);
        btnRmAnggota.addActionListener(e);
        btnLogout.addActionListener(e);
        btnReplacePembimbing.addActionListener(e);
        btnRmKelompokTA.addActionListener(e);
        btnAddKelompokTA.addActionListener(e);
    }
}
