/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author agungrb
 */
public class OlahDataMahasiswa extends javax.swing.JFrame implements View {

    /**
     * Creates new form OlahDataMahasiswa
     */
    public OlahDataMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRevisiTA = new javax.swing.JButton();
        btnCreateTA = new javax.swing.JButton();
        btnRegTA = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txFieldNama = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olah Data Mahasiswa");

        btnRevisiTA.setText("Revisi Judul TA");

        btnCreateTA.setText("Buat Tugas Akhir");

        btnRegTA.setText("Registrasi TA");
        btnRegTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegTAActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("OLAH DATA MAHASISWA");

        txFieldNama.setEditable(false);
        txFieldNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txFieldNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFieldNama.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txFieldNama))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCreateTA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegTA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRevisiTA, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRevisiTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegTAActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnCreateTA() {
        return btnCreateTA;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnRegTA() {
        return btnRegTA;
    }

    public JButton getBtnRevisiTA() {
        return btnRevisiTA;
    }

    public void setTxFieldNama(String s) {
        txFieldNama.setText(s);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTA;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegTA;
    private javax.swing.JButton btnRevisiTA;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JTextField txFieldNama;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(ActionListener e) {
        btnCreateTA.addActionListener(e);
        btnLogout.addActionListener(e);
        btnRevisiTA.addActionListener(e);
        btnRegTA.addActionListener(e);
    }
}
