/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author agungrb
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameOlahDataDosen = new javax.swing.JFrame();
        jLabel32 = new javax.swing.JLabel();
        btnAddKelompokTA = new javax.swing.JButton();
        btnRmKelompokTA = new javax.swing.JButton();
        btnAddAnggota = new javax.swing.JButton();
        btnRmAnggota = new javax.swing.JButton();
        btnReplacePembimbing = new javax.swing.JButton();
        btnLogoutDosen = new javax.swing.JButton();
        txFieldSetNamaDosen = new javax.swing.JTextField();
        frameOlahDataMahasiswa = new javax.swing.JFrame();
        btnCreateTA = new javax.swing.JButton();
        btnRegTA = new javax.swing.JButton();
        btnLogoutMahasiswa = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnRevisiTA = new javax.swing.JButton();
        panelViewDataDosen = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txFieldShowNamaDosen = new javax.swing.JTextField();
        txFieldShowStatusDosen = new javax.swing.JTextField();
        txFieldShowJumlahKelompokTA = new javax.swing.JTextField();
        btnOKViewDataDosen = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txFieldGetIdDosen = new javax.swing.JTextField();
        txFieldShowNIP = new javax.swing.JTextField();
        txFieldKelompokTATerdaftar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        panelViewDataMahasiswa = new javax.swing.JPanel();
        txFieldGetIdMahasiswa = new javax.swing.JTextField();
        txFieldShowNIM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnOKViewDataMahasiswa = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txFieldShowJumlahSKS = new javax.swing.JTextField();
        txFieldShowStatusKP = new javax.swing.JTextField();
        txFieldShowNamaMahasiswa = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txFieldJudulTA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txFieldPemb1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txFieldPemb2 = new javax.swing.JTextField();
        panelRegMahasiswa = new javax.swing.JPanel();
        txFieldNamaMahasiswa = new javax.swing.JTextField();
        txFieldNIM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCancelRegMahasiswa = new javax.swing.JButton();
        btnSubmitRegMahasiswa = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmBoxStatusKP = new javax.swing.JComboBox<>();
        txFieldJumlahSKS = new javax.swing.JTextField();
        txFieldPswMahasiswa = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        panelRegDosen = new javax.swing.JPanel();
        txFieldNamaDosen = new javax.swing.JTextField();
        txFieldNIP = new javax.swing.JTextField();
        txFieldJumlahKelompokTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelRegDosen = new javax.swing.JButton();
        btnSubmitRegDosen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmBoxStatusPembimbing = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txFieldPswDosen = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        panelLoginMahasiswa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txFieldIdMahasiswa = new javax.swing.JTextField();
        pswFieldMahasiswa = new javax.swing.JPasswordField();
        btnLoginMahasiswa = new javax.swing.JButton();
        panelLoginDosen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txFieldIdDosen = new javax.swing.JTextField();
        pswFieldDosen = new javax.swing.JPasswordField();
        btnLoginDosen = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuBukaFile = new javax.swing.JMenuItem();
        menuSimpanFile = new javax.swing.JMenuItem();
        menuLogin = new javax.swing.JMenu();
        menuLoginDosen = new javax.swing.JMenuItem();
        menuLoginMahasiswa = new javax.swing.JMenuItem();
        menuRegistrasi = new javax.swing.JMenu();
        menuRegDosen = new javax.swing.JMenuItem();
        menuRegMahasiswa = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuViewDataDosen = new javax.swing.JMenuItem();
        menuViewDataMahasiswa = new javax.swing.JMenuItem();

        frameOlahDataDosen.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameOlahDataDosen.setTitle("Olah Data Dosen");
        frameOlahDataDosen.setResizable(false);
        frameOlahDataDosen.setSize(new java.awt.Dimension(244, 350));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("OLAH DATA DOSEN");

        btnAddKelompokTA.setText("Add Kelompok TA");

        btnRmKelompokTA.setText("Remove Kelompok TA");
        btnRmKelompokTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmKelompokTAActionPerformed(evt);
            }
        });

        btnAddAnggota.setText("Add Anggota");
        btnAddAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnggotaActionPerformed(evt);
            }
        });

        btnRmAnggota.setText("Remove Anggota");

        btnReplacePembimbing.setText("Replace Pembimbing");
        btnReplacePembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplacePembimbingActionPerformed(evt);
            }
        });

        btnLogoutDosen.setText("Logout");
        btnLogoutDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutDosenActionPerformed(evt);
            }
        });

        txFieldSetNamaDosen.setEditable(false);
        txFieldSetNamaDosen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txFieldSetNamaDosen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFieldSetNamaDosen.setBorder(null);

        javax.swing.GroupLayout frameOlahDataDosenLayout = new javax.swing.GroupLayout(frameOlahDataDosen.getContentPane());
        frameOlahDataDosen.getContentPane().setLayout(frameOlahDataDosenLayout);
        frameOlahDataDosenLayout.setHorizontalGroup(
            frameOlahDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOlahDataDosenLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(frameOlahDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRmKelompokTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddKelompokTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRmAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReplacePembimbing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogoutDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameOlahDataDosenLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(frameOlahDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txFieldSetNamaDosen))
                .addGap(37, 37, 37))
        );
        frameOlahDataDosenLayout.setVerticalGroup(
            frameOlahDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOlahDataDosenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel32)
                .addGap(1, 1, 1)
                .addComponent(txFieldSetNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddKelompokTA)
                .addGap(18, 18, 18)
                .addComponent(btnRmKelompokTA)
                .addGap(18, 18, 18)
                .addComponent(btnAddAnggota)
                .addGap(18, 18, 18)
                .addComponent(btnRmAnggota)
                .addGap(18, 18, 18)
                .addComponent(btnReplacePembimbing)
                .addGap(18, 18, 18)
                .addComponent(btnLogoutDosen)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        frameOlahDataMahasiswa.setResizable(false);
        frameOlahDataMahasiswa.setSize(new java.awt.Dimension(230, 220));

        btnCreateTA.setText("Buat Tugas Akhir");

        btnRegTA.setText("Registrasi Tugas Akhir");
        btnRegTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegTAActionPerformed(evt);
            }
        });

        btnLogoutMahasiswa.setText("Logout");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("OLAH DATA MAHASISWA");

        btnRevisiTA.setText("Revisi Judul TA");

        javax.swing.GroupLayout frameOlahDataMahasiswaLayout = new javax.swing.GroupLayout(frameOlahDataMahasiswa.getContentPane());
        frameOlahDataMahasiswa.getContentPane().setLayout(frameOlahDataMahasiswaLayout);
        frameOlahDataMahasiswaLayout.setHorizontalGroup(
            frameOlahDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOlahDataMahasiswaLayout.createSequentialGroup()
                .addGroup(frameOlahDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameOlahDataMahasiswaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel15))
                    .addGroup(frameOlahDataMahasiswaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(frameOlahDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegTA, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(btnCreateTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogoutMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRevisiTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        frameOlahDataMahasiswaLayout.setVerticalGroup(
            frameOlahDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameOlahDataMahasiswaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRevisiTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogoutMahasiswa)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi TA");
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("LIHAT DATA DOSEN");

        txFieldShowNamaDosen.setEditable(false);
        txFieldShowNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNamaDosenActionPerformed(evt);
            }
        });

        txFieldShowStatusDosen.setEditable(false);
        txFieldShowStatusDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowStatusDosenActionPerformed(evt);
            }
        });

        txFieldShowJumlahKelompokTA.setEditable(false);
        txFieldShowJumlahKelompokTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowJumlahKelompokTAActionPerformed(evt);
            }
        });

        btnOKViewDataDosen.setText("OK");
        btnOKViewDataDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKViewDataDosenActionPerformed(evt);
            }
        });

        jLabel18.setText("Pembimbing ke-");

        jLabel19.setText("Jumlah Kelompok TA");

        jLabel20.setText("NIP");

        jLabel21.setText("Nama");

        jLabel22.setText("ID Dosen");

        txFieldGetIdDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldGetIdDosenActionPerformed(evt);
            }
        });

        txFieldShowNIP.setEditable(false);
        txFieldShowNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNIPActionPerformed(evt);
            }
        });

        txFieldKelompokTATerdaftar.setEditable(false);

        jLabel14.setText("Kelompok TA terdaftar");

        javax.swing.GroupLayout panelViewDataDosenLayout = new javax.swing.GroupLayout(panelViewDataDosen);
        panelViewDataDosen.setLayout(panelViewDataDosenLayout);
        panelViewDataDosenLayout.setHorizontalGroup(
            panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataDosenLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFieldGetIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFieldShowNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFieldShowNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFieldShowStatusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnOKViewDataDosen))
                            .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txFieldKelompokTATerdaftar)
                                .addComponent(txFieldShowJumlahKelompokTA, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        panelViewDataDosenLayout.setVerticalGroup(
            panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldGetIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txFieldShowNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowStatusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(3, 3, 3)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldKelompokTATerdaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOKViewDataDosen)
                .addContainerGap())
        );

        txFieldGetIdMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldGetIdMahasiswaActionPerformed(evt);
            }
        });

        txFieldShowNIM.setEditable(false);
        txFieldShowNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNIMActionPerformed(evt);
            }
        });

        jLabel17.setText("ID Mahasiswa");

        jLabel23.setText("NIM");

        jLabel24.setText("Jumlah SKS");

        jLabel25.setText("Status KP");

        btnOKViewDataMahasiswa.setText("OK");
        btnOKViewDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKViewDataMahasiswaActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("LIHAT DATA MAHASISWA");

        txFieldShowJumlahSKS.setEditable(false);
        txFieldShowJumlahSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowJumlahSKSActionPerformed(evt);
            }
        });

        txFieldShowStatusKP.setEditable(false);
        txFieldShowStatusKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowStatusKPActionPerformed(evt);
            }
        });

        txFieldShowNamaMahasiswa.setEditable(false);
        txFieldShowNamaMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNamaMahasiswaActionPerformed(evt);
            }
        });

        jLabel27.setText("Nama");

        txFieldJudulTA.setEditable(false);
        txFieldJudulTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldJudulTAActionPerformed(evt);
            }
        });

        jLabel3.setText("Judul TA");

        txFieldPemb1.setEditable(false);
        txFieldPemb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldPemb1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Pembimbing 1");

        jLabel29.setText("Pembimbing 2");

        txFieldPemb2.setEditable(false);
        txFieldPemb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldPemb2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewDataMahasiswaLayout = new javax.swing.GroupLayout(panelViewDataMahasiswa);
        panelViewDataMahasiswa.setLayout(panelViewDataMahasiswaLayout);
        panelViewDataMahasiswaLayout.setHorizontalGroup(
            panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataMahasiswaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelViewDataMahasiswaLayout.createSequentialGroup()
                        .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel3)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(43, 43, 43)
                        .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldGetIdMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txFieldShowNamaMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txFieldShowNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txFieldShowJumlahSKS, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txFieldShowStatusKP, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txFieldJudulTA)
                            .addComponent(txFieldPemb1)
                            .addComponent(txFieldPemb2)))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataMahasiswaLayout.createSequentialGroup()
                        .addComponent(btnOKViewDataMahasiswa)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataMahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(93, 93, 93))))
        );
        panelViewDataMahasiswaLayout.setVerticalGroup(
            panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldGetIdMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txFieldShowNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txFieldShowJumlahSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowStatusKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldJudulTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldPemb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldPemb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(21, 21, 21)
                .addComponent(btnOKViewDataMahasiswa)
                .addGap(22, 22, 22))
        );

        txFieldNamaMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNamaMahasiswaActionPerformed(evt);
            }
        });

        txFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNIMActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama");

        jLabel10.setText("NIM");

        jLabel11.setText("Jumlah SKS");

        jLabel12.setText("Status KP");

        btnCancelRegMahasiswa.setText("Cancel");
        btnCancelRegMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegMahasiswaActionPerformed(evt);
            }
        });

        btnSubmitRegMahasiswa.setText("Submit");
        btnSubmitRegMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRegMahasiswaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("REGISTRASI MAHASISWA");

        cmBoxStatusKP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sudah", "belum" }));
        cmBoxStatusKP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmBoxStatusKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBoxStatusKPActionPerformed(evt);
            }
        });

        txFieldJumlahSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldJumlahSKSActionPerformed(evt);
            }
        });

        jLabel30.setText("Password");

        javax.swing.GroupLayout panelRegMahasiswaLayout = new javax.swing.GroupLayout(panelRegMahasiswa);
        panelRegMahasiswa.setLayout(panelRegMahasiswaLayout);
        panelRegMahasiswaLayout.setHorizontalGroup(
            panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                        .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(72, 72, 72))
                            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmBoxStatusKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldNIM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txFieldJumlahSKS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegMahasiswaLayout.createSequentialGroup()
                        .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldPswMahasiswa)
                            .addComponent(txFieldNamaMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegMahasiswaLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnSubmitRegMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCancelRegMahasiswa)
                .addGap(99, 99, 99))
            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegMahasiswaLayout.setVerticalGroup(
            panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldPswMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txFieldJumlahSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmBoxStatusKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelRegMahasiswa)
                    .addComponent(btnSubmitRegMahasiswa))
                .addGap(47, 47, 47))
        );

        txFieldNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNamaDosenActionPerformed(evt);
            }
        });

        txFieldNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNIPActionPerformed(evt);
            }
        });

        txFieldJumlahKelompokTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldJumlahKelompokTAActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        jLabel5.setText("NIP");

        jLabel7.setText("Jumlah Kelompok TA");

        btnCancelRegDosen.setText("Cancel");
        btnCancelRegDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegDosenActionPerformed(evt);
            }
        });

        btnSubmitRegDosen.setText("Submit");
        btnSubmitRegDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRegDosenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("REGISTRASI DOSEN");

        cmBoxStatusPembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        jLabel16.setText("Pembimbing ke-");

        jLabel31.setText("Password");

        javax.swing.GroupLayout panelRegDosenLayout = new javax.swing.GroupLayout(panelRegDosen);
        panelRegDosen.setLayout(panelRegDosenLayout);
        panelRegDosenLayout.setHorizontalGroup(
            panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmBoxStatusPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txFieldJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldPswDosen)
                            .addComponent(txFieldNamaDosen, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnSubmitRegDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelRegDosen)
                .addGap(99, 99, 99))
            .addGroup(panelRegDosenLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegDosenLayout.setVerticalGroup(
            panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldPswDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmBoxStatusPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelRegDosen)
                    .addComponent(btnSubmitRegDosen))
                .addGap(47, 47, 47))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MENU LOGIN MAHASISWA");

        txFieldIdMahasiswa.setText("ID Mahasiswa");

        pswFieldMahasiswa.setText("00000");

        btnLoginMahasiswa.setText("Login");

        javax.swing.GroupLayout panelLoginMahasiswaLayout = new javax.swing.GroupLayout(panelLoginMahasiswa);
        panelLoginMahasiswa.setLayout(panelLoginMahasiswaLayout);
        panelLoginMahasiswaLayout.setHorizontalGroup(
            panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                .addGroup(panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldIdMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswFieldMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnLoginMahasiswa)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelLoginMahasiswaLayout.setVerticalGroup(
            panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldIdMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswFieldMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginMahasiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLoginDosen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("MENU LOGIN DOSEN");

        txFieldIdDosen.setText("ID Dosen");

        pswFieldDosen.setText("00000");
        pswFieldDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswFieldDosenActionPerformed(evt);
            }
        });

        btnLoginDosen.setText("Login");

        javax.swing.GroupLayout panelLoginDosenLayout = new javax.swing.GroupLayout(panelLoginDosen);
        panelLoginDosen.setLayout(panelLoginDosenLayout);
        panelLoginDosenLayout.setHorizontalGroup(
            panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginDosenLayout.createSequentialGroup()
                .addGroup(panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginDosenLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldIdDosen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswFieldDosen, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelLoginDosenLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnLoginDosen)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelLoginDosenLayout.setVerticalGroup(
            panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswFieldDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginDosen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        menuBukaFile.setText("Buka file");
        menuFile.add(menuBukaFile);

        menuSimpanFile.setText("Simpan file");
        menuFile.add(menuSimpanFile);

        menuBar.add(menuFile);

        menuLogin.setText("Login");

        menuLoginDosen.setText("Login Dosen");
        menuLogin.add(menuLoginDosen);

        menuLoginMahasiswa.setText("Login Mahasiswa");
        menuLogin.add(menuLoginMahasiswa);

        menuBar.add(menuLogin);

        menuRegistrasi.setText("Registrasi");

        menuRegDosen.setText("Reg. Dosen");
        menuRegistrasi.add(menuRegDosen);

        menuRegMahasiswa.setText("Reg. Mahasiswa");
        menuRegistrasi.add(menuRegMahasiswa);

        menuBar.add(menuRegistrasi);

        menuView.setText("View");

        menuViewDataDosen.setText("Data Dosen");
        menuView.add(menuViewDataDosen);

        menuViewDataMahasiswa.setText("Data Mahasiswa");
        menuView.add(menuViewDataMahasiswa);

        menuBar.add(menuView);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelViewDataDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelViewDataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelViewDataDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelViewDataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txFieldNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNamaDosenActionPerformed

    private void txFieldNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNIPActionPerformed

    private void txFieldJumlahKelompokTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldJumlahKelompokTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldJumlahKelompokTAActionPerformed

    private void btnCancelRegDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRegDosenActionPerformed

    private void btnSubmitRegDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRegDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitRegDosenActionPerformed

    private void btnSubmitRegMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRegMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitRegMahasiswaActionPerformed

    private void txFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNIMActionPerformed

    private void txFieldNamaMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNamaMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNamaMahasiswaActionPerformed

    private void txFieldJumlahSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldJumlahSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldJumlahSKSActionPerformed

    private void txFieldShowNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNamaDosenActionPerformed

    private void txFieldShowStatusDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowStatusDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowStatusDosenActionPerformed

    private void txFieldShowJumlahKelompokTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowJumlahKelompokTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowJumlahKelompokTAActionPerformed

    private void btnOKViewDataDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKViewDataDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOKViewDataDosenActionPerformed

    private void txFieldGetIdDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldGetIdDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldGetIdDosenActionPerformed

    private void txFieldShowNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNIPActionPerformed

    private void cmBoxStatusKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBoxStatusKPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmBoxStatusKPActionPerformed

    private void btnCancelRegMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRegMahasiswaActionPerformed

    private void txFieldGetIdMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldGetIdMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldGetIdMahasiswaActionPerformed

    private void txFieldShowNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNIMActionPerformed

    private void btnOKViewDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKViewDataMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOKViewDataMahasiswaActionPerformed

    private void txFieldShowJumlahSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowJumlahSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowJumlahSKSActionPerformed

    private void txFieldShowStatusKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowStatusKPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowStatusKPActionPerformed

    private void txFieldShowNamaMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNamaMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNamaMahasiswaActionPerformed

    private void btnAddAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAnggotaActionPerformed

    private void btnLogoutDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutDosenActionPerformed

    private void btnRmKelompokTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmKelompokTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRmKelompokTAActionPerformed

    private void btnReplacePembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplacePembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReplacePembimbingActionPerformed

    private void btnRegTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegTAActionPerformed

    private void txFieldJudulTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldJudulTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldJudulTAActionPerformed

    private void txFieldPemb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldPemb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldPemb1ActionPerformed

    private void txFieldPemb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldPemb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldPemb2ActionPerformed

    private void pswFieldDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswFieldDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswFieldDosenActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //GETTER TEXT FIELD, COMBO BOX, etc
    public int getTxFieldIdDosen() {
        return Integer.parseInt(txFieldIdDosen.getText());
    }
    public String getPswFieldDosen() {
        return pswFieldDosen.getText();
    }
    public int getTxFieldIdMahasiswa() {
        return Integer.parseInt(txFieldIdMahasiswa.getText());
    }
    public String getPswFieldMahasiswa() {
        return pswFieldMahasiswa.getText();
    }
    public String getTxFieldNamaDosen() {
        return txFieldNamaDosen.getText();
    }
    public int getTxFieldJumlahSKS() {
        return Integer.parseInt(txFieldJumlahSKS.getText());
    }
    public long getTxFieldNIM() {
        return Long.parseLong(txFieldNIM.getText());
    }
    public String getTxFieldNamaMahasiswa() {
        return txFieldNamaMahasiswa.getText();
    } 
    public int getTxFieldJumlahKelompokTA() {
        return Integer.parseInt(txFieldJumlahKelompokTA.getText());
    }
    public long getTxFieldNIP() {
        return Long.parseLong(txFieldNIP.getText());
    }
    public int getCmBoxStatusPembimbing() {
        return cmBoxStatusPembimbing.getSelectedIndex()+1;
    }
    public boolean getCmBoxStatusKP() {
        if(cmBoxStatusKP.getSelectedIndex() == 0) {
            return true;
        }
        else {
            return false;
        }
    }
    public int getTxFieldGetIdDosen() {
        return Integer.parseInt(txFieldGetIdDosen.getText());
    }
    public int getTxFieldGetIdMahasiswa() {
        return Integer.parseInt(txFieldGetIdMahasiswa.getText());
    }
    public String getTxFieldPswMahasiswa() {
        return txFieldPswMahasiswa.getText();
    }
    public String getTxFieldPswDosen() {
        return txFieldPswDosen.getText();
    }
    
    
    
    //GETTER MENU, BUTTON, etc
    public Object getBtnLoginDosen() {
        return btnLoginDosen;
    }
    public Object getBtnLoginMahasiswa() {
        return btnLoginMahasiswa;
    }
    public Object getMenuLoginDosen() {
        return menuLoginDosen;
    }
    public Object getMenuLoginMahasiswa() {
        return menuLoginMahasiswa;
    }
    public Object getBtnCancelRegMahasiswa() {
        return btnCancelRegMahasiswa;
    }
    public Object getBtnSubmitRegMahasiswa() {
        return btnSubmitRegMahasiswa;
    }
    public Object getBtnCancelRegDosen() {
        return btnCancelRegDosen;
    }
    public Object getBtnSubmitRegDosen() {
        return btnSubmitRegDosen;
    }
    public Object getBtnOKViewDataDosen() {
        return btnOKViewDataDosen;
    }
    public Object getBtnOKViewDataMahasiswa() {
        return btnOKViewDataMahasiswa;
    } 
    public Object getMenuBukaFile() {
        return menuBukaFile;
    }
    public Object getMenuSimpanFile() {
        return menuSimpanFile;
    }
    public Object getMenuRegDosen() {
        return menuRegDosen;
    }
    public Object getMenuRegMahasiswa() {
        return menuRegMahasiswa;
    }
    public Object getMenuViewDataDosen() {
        return menuViewDataDosen;
    }
    public Object getMenuViewDataMahasiswa() {
        return menuViewDataMahasiswa;
    }

    public Object getBtnAddAnggota() {
        return btnAddAnggota;
    }

    public Object getBtnAddKelompokTA() {
        return btnAddKelompokTA;
    }

    public Object getBtnLogoutDosen() {
        return btnLogoutDosen;
    }

    public Object getBtnReplacePembimbing() {
        return btnReplacePembimbing;
    }

    public Object getBtnRmAnggota() {
        return btnRmAnggota;
    }

    public Object getBtnRmKelompokTA() {
        return btnRmKelompokTA;
    }

    public Object getBtnCreateTA() {
        return btnCreateTA;
    }

    public Object getBtnLogoutMahasiswa() {
        return btnLogoutMahasiswa;
    }

    public Object getBtnRegTA() {
        return btnRegTA;
    }

    public Object getBtnRevisiTA() {
        return btnRevisiTA;
    }
    
    
    
    
    //GETTER PANEL, etc
    public JPanel getPanelLoginDosen() {
        return panelLoginDosen;
    }
    public JPanel getPanelLoginMahasiswa() {
        return panelLoginMahasiswa;
    }
    public JPanel getPanelRegDosen() {
        return panelRegDosen;
    }
    public JPanel getPanelRegMahasiswa() {
        return panelRegMahasiswa;
    }
    public JPanel getPanelViewDataDosen() {
        return panelViewDataDosen;
    }
    public JPanel getPanelViewDataMahasiswa() {
        return panelViewDataMahasiswa;
    }
    public JFrame getFrameOlahDataDosen() {
        return frameOlahDataDosen;
    }
    public JFrame getFrameOlahDataMahasiswa() {
        return frameOlahDataMahasiswa;
    } 
    
    
    
    
    //SETTER TEXT FIELD, etc
    public void setTxFieldShowNamaDosen(String nama) {
        txFieldShowNamaDosen.setText(nama);
    }
    public void setTxFieldShowNIP(long nip) {
        txFieldShowNIP.setText(Long.toString(nip));
    }
    public void setTxFieldShowStatusDosen(int status) {
        txFieldShowStatusDosen.setText(Integer.toString(status));
    }
    public void setTxFieldShowJumlahKelompokTA(int jumlah) {
        txFieldShowJumlahKelompokTA.setText(Integer.toString(jumlah));
    }
    public void setTxFieldShowJumlahSKS(int jumlahSKS) {
        txFieldShowJumlahSKS.setText(Integer.toString(jumlahSKS));
    }
    public void setTxFieldShowNIM(long nim) {
        txFieldShowNIM.setText(Long.toString(nim));
    }
    public void setTxFieldShowNamaMahasiswa(String nama) {
        txFieldShowNamaMahasiswa.setText(nama);
    }
    public void setTxFieldShowStatusKP(boolean statusKP) {
        if(statusKP) {
            txFieldShowStatusKP.setText("Sudah");
        }
        else {
            txFieldShowStatusKP.setText("Belum");    
        }
    }
    public void setTxFieldSetNamaDosen(String nama) {
        txFieldSetNamaDosen.setText("Hai, "+nama);
    }
    public void setTxFieldKelompokTATerdaftar(int jum) {
        txFieldKelompokTATerdaftar.setText(Integer.toString(jum));
    }

    public void setTxFieldJudulTA(String s) {
        txFieldJudulTA.setText(s);
    }
    public void setTxFieldPemb1(String s) {
        this.txFieldPemb1.setText(s);
    }
    public void setTxFieldPemb2(String s) {
        this.txFieldPemb2.setText(s);
    }
    
    
    
    
    
    public void addListener(ActionListener e) {
        menuViewDataDosen.addActionListener(e);
        menuViewDataMahasiswa.addActionListener(e);
        menuBukaFile.addActionListener(e);
        menuSimpanFile.addActionListener(e);
        menuLoginMahasiswa.addActionListener(e);
        menuLoginDosen.addActionListener(e);
        menuRegDosen.addActionListener(e);
        menuRegMahasiswa.addActionListener(e);
        
        btnLoginDosen.addActionListener(e);
        btnLoginMahasiswa.addActionListener(e);
        btnSubmitRegDosen.addActionListener(e);
        btnCancelRegDosen.addActionListener(e);
        btnCancelRegMahasiswa.addActionListener(e);
        btnSubmitRegMahasiswa.addActionListener(e);
        btnOKViewDataDosen.addActionListener(e);
        btnAddKelompokTA.addActionListener(e);
        btnRmKelompokTA.addActionListener(e);
        btnAddAnggota.addActionListener(e);
        btnRmAnggota.addActionListener(e);
        btnReplacePembimbing.addActionListener(e);
        btnLogoutDosen.addActionListener(e);
        btnLogoutMahasiswa.addActionListener(e);
        btnCreateTA.addActionListener(e);
        btnRegTA.addActionListener(e);
        btnRevisiTA.addActionListener(e);
        
        cmBoxStatusPembimbing.addActionListener(e);
        btnOKViewDataMahasiswa.addActionListener(e);
        cmBoxStatusKP.addActionListener(e);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnggota;
    private javax.swing.JButton btnAddKelompokTA;
    private javax.swing.JButton btnCancelRegDosen;
    private javax.swing.JButton btnCancelRegMahasiswa;
    private javax.swing.JButton btnCreateTA;
    private javax.swing.JButton btnLoginDosen;
    private javax.swing.JButton btnLoginMahasiswa;
    private javax.swing.JButton btnLogoutDosen;
    private javax.swing.JButton btnLogoutMahasiswa;
    private javax.swing.JButton btnOKViewDataDosen;
    private javax.swing.JButton btnOKViewDataMahasiswa;
    private javax.swing.JButton btnRegTA;
    private javax.swing.JButton btnReplacePembimbing;
    private javax.swing.JButton btnRevisiTA;
    private javax.swing.JButton btnRmAnggota;
    private javax.swing.JButton btnRmKelompokTA;
    private javax.swing.JButton btnSubmitRegDosen;
    private javax.swing.JButton btnSubmitRegMahasiswa;
    private javax.swing.JComboBox<String> cmBoxStatusKP;
    private javax.swing.JComboBox<String> cmBoxStatusPembimbing;
    private javax.swing.JFrame frameOlahDataDosen;
    private javax.swing.JFrame frameOlahDataMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBukaFile;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenuItem menuLoginDosen;
    private javax.swing.JMenuItem menuLoginMahasiswa;
    private javax.swing.JMenuItem menuRegDosen;
    private javax.swing.JMenuItem menuRegMahasiswa;
    private javax.swing.JMenu menuRegistrasi;
    private javax.swing.JMenuItem menuSimpanFile;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem menuViewDataDosen;
    private javax.swing.JMenuItem menuViewDataMahasiswa;
    private javax.swing.JPanel panelLoginDosen;
    private javax.swing.JPanel panelLoginMahasiswa;
    private javax.swing.JPanel panelRegDosen;
    private javax.swing.JPanel panelRegMahasiswa;
    private javax.swing.JPanel panelViewDataDosen;
    private javax.swing.JPanel panelViewDataMahasiswa;
    private javax.swing.JPasswordField pswFieldDosen;
    private javax.swing.JPasswordField pswFieldMahasiswa;
    private javax.swing.JTextField txFieldGetIdDosen;
    private javax.swing.JTextField txFieldGetIdMahasiswa;
    private javax.swing.JTextField txFieldIdDosen;
    private javax.swing.JTextField txFieldIdMahasiswa;
    private javax.swing.JTextField txFieldJudulTA;
    private javax.swing.JTextField txFieldJumlahKelompokTA;
    private javax.swing.JTextField txFieldJumlahSKS;
    private javax.swing.JTextField txFieldKelompokTATerdaftar;
    private javax.swing.JTextField txFieldNIM;
    private javax.swing.JTextField txFieldNIP;
    private javax.swing.JTextField txFieldNamaDosen;
    private javax.swing.JTextField txFieldNamaMahasiswa;
    private javax.swing.JTextField txFieldPemb1;
    private javax.swing.JTextField txFieldPemb2;
    private javax.swing.JTextField txFieldPswDosen;
    private javax.swing.JTextField txFieldPswMahasiswa;
    private javax.swing.JTextField txFieldSetNamaDosen;
    private javax.swing.JTextField txFieldShowJumlahKelompokTA;
    private javax.swing.JTextField txFieldShowJumlahSKS;
    private javax.swing.JTextField txFieldShowNIM;
    private javax.swing.JTextField txFieldShowNIP;
    private javax.swing.JTextField txFieldShowNamaDosen;
    private javax.swing.JTextField txFieldShowNamaMahasiswa;
    private javax.swing.JTextField txFieldShowStatusDosen;
    private javax.swing.JTextField txFieldShowStatusKP;
    // End of variables declaration//GEN-END:variables
}
