/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author agungrb
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSelamatDatang = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txFieldSelamatDatang = new javax.swing.JTextField();
        btnOKSelamatDatang = new javax.swing.JButton();
        dialogRegistrasiBerhasil = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        btnOKBerhasil = new javax.swing.JButton();
        txFieldBerhasil = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        frameOlahDataDosen = new javax.swing.JFrame();
        frameOlahDataMahasiswa = new javax.swing.JFrame();
        dialogUserPswSalah = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btnOKUserPswSalah = new javax.swing.JButton();
        dialogTidakDitemukan = new javax.swing.JDialog();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnOKTidakDitemukan = new javax.swing.JButton();
        panelViewDataMahasiswa = new javax.swing.JPanel();
        txFieldGetIdMahasiswa = new javax.swing.JTextField();
        txFieldShowNIM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnOKViewDataMahasiswa = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txFieldShowJumlahSKS = new javax.swing.JTextField();
        txFieldShowStatusKP = new javax.swing.JTextField();
        txFieldShowNamaMahasiswa = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        panelViewDataDosen = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txFieldShowNamaDosen = new javax.swing.JTextField();
        txFieldShowStatusDosen = new javax.swing.JTextField();
        txFieldShowJumlahKelompokTA = new javax.swing.JTextField();
        btnOKViewDataDosen = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txFieldGetIdDosen = new javax.swing.JTextField();
        txFieldShowNIP = new javax.swing.JTextField();
        panelLoginDosen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txFieldIdDosen = new javax.swing.JTextField();
        pswFieldDosen = new javax.swing.JPasswordField();
        btnLoginDosen = new javax.swing.JButton();
        panelLoginMahasiswa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txFieldIdMahasiswa = new javax.swing.JTextField();
        pswFieldMahasiswa = new javax.swing.JPasswordField();
        btnLoginMahasiswa = new javax.swing.JButton();
        panelRegDosen = new javax.swing.JPanel();
        txFieldNamaDosen = new javax.swing.JTextField();
        txFieldNIP = new javax.swing.JTextField();
        txFieldJumlahKelompokTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelRegDosen = new javax.swing.JButton();
        btnSubmitRegDosen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmBoxStatusPembimbing = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        panelRegMahasiswa = new javax.swing.JPanel();
        txFieldNamaMahasiswa = new javax.swing.JTextField();
        txFieldNIM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCancelRegMahasiswa = new javax.swing.JButton();
        btnSubmitRegMahasiswa = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cmBoxStatusKP = new javax.swing.JComboBox<>();
        txFieldJumlahSKS = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuBukaFile = new javax.swing.JMenuItem();
        menuSimpanFile = new javax.swing.JMenuItem();
        menuLogin = new javax.swing.JMenu();
        menuLoginDosen = new javax.swing.JMenuItem();
        menuLoginMahasiswa = new javax.swing.JMenuItem();
        menuRegistrasi = new javax.swing.JMenu();
        menuRegDosen = new javax.swing.JMenuItem();
        menuRegMahasiswa = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuViewDataDosen = new javax.swing.JMenuItem();
        menuViewDataMahasiswa = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();

        dialogSelamatDatang.setLocation(new java.awt.Point(0, 0));
        dialogSelamatDatang.setResizable(false);
        dialogSelamatDatang.setSize(new java.awt.Dimension(185, 130));
        dialogSelamatDatang.setType(java.awt.Window.Type.POPUP);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selamat Datang");

        txFieldSelamatDatang.setEditable(false);
        txFieldSelamatDatang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txFieldSelamatDatang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFieldSelamatDatang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOKSelamatDatang.setText("OK");

        javax.swing.GroupLayout dialogSelamatDatangLayout = new javax.swing.GroupLayout(dialogSelamatDatang.getContentPane());
        dialogSelamatDatang.getContentPane().setLayout(dialogSelamatDatangLayout);
        dialogSelamatDatangLayout.setHorizontalGroup(
            dialogSelamatDatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                .addGroup(dialogSelamatDatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnOKSelamatDatang)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(txFieldSelamatDatang)
        );
        dialogSelamatDatangLayout.setVerticalGroup(
            dialogSelamatDatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldSelamatDatang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOKSelamatDatang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogRegistrasiBerhasil.setTitle("Notifikasi");
        dialogRegistrasiBerhasil.setSize(new java.awt.Dimension(181, 109));
        dialogRegistrasiBerhasil.setType(java.awt.Window.Type.POPUP);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Registrasi Berhasil");

        btnOKBerhasil.setText("OK");
        btnOKBerhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKBerhasilActionPerformed(evt);
            }
        });

        txFieldBerhasil.setEditable(false);
        txFieldBerhasil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txFieldBerhasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txFieldBerhasil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("ID:");

        javax.swing.GroupLayout dialogRegistrasiBerhasilLayout = new javax.swing.GroupLayout(dialogRegistrasiBerhasil.getContentPane());
        dialogRegistrasiBerhasil.getContentPane().setLayout(dialogRegistrasiBerhasilLayout);
        dialogRegistrasiBerhasilLayout.setHorizontalGroup(
            dialogRegistrasiBerhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegistrasiBerhasilLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnOKBerhasil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRegistrasiBerhasilLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRegistrasiBerhasilLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addGap(33, 33, 33)
                .addComponent(txFieldBerhasil)
                .addContainerGap())
        );
        dialogRegistrasiBerhasilLayout.setVerticalGroup(
            dialogRegistrasiBerhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegistrasiBerhasilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogRegistrasiBerhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldBerhasil, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOKBerhasil)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameOlahDataDosenLayout = new javax.swing.GroupLayout(frameOlahDataDosen.getContentPane());
        frameOlahDataDosen.getContentPane().setLayout(frameOlahDataDosenLayout);
        frameOlahDataDosenLayout.setHorizontalGroup(
            frameOlahDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frameOlahDataDosenLayout.setVerticalGroup(
            frameOlahDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout frameOlahDataMahasiswaLayout = new javax.swing.GroupLayout(frameOlahDataMahasiswa.getContentPane());
        frameOlahDataMahasiswa.getContentPane().setLayout(frameOlahDataMahasiswaLayout);
        frameOlahDataMahasiswaLayout.setHorizontalGroup(
            frameOlahDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frameOlahDataMahasiswaLayout.setVerticalGroup(
            frameOlahDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        dialogUserPswSalah.setTitle("Peringatan");
        dialogUserPswSalah.setResizable(false);
        dialogUserPswSalah.setSize(new java.awt.Dimension(185, 130));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("ID ATAU PASSWORD");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setText("SALAH!!");

        btnOKUserPswSalah.setText("OK");

        javax.swing.GroupLayout dialogUserPswSalahLayout = new javax.swing.GroupLayout(dialogUserPswSalah.getContentPane());
        dialogUserPswSalah.getContentPane().setLayout(dialogUserPswSalahLayout);
        dialogUserPswSalahLayout.setHorizontalGroup(
            dialogUserPswSalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogUserPswSalahLayout.createSequentialGroup()
                .addGroup(dialogUserPswSalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogUserPswSalahLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel28))
                    .addGroup(dialogUserPswSalahLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel29))
                    .addGroup(dialogUserPswSalahLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnOKUserPswSalah)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        dialogUserPswSalahLayout.setVerticalGroup(
            dialogUserPswSalahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogUserPswSalahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOKUserPswSalah)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        dialogTidakDitemukan.setPreferredSize(new java.awt.Dimension(181, 130));
        dialogTidakDitemukan.setResizable(false);
        dialogTidakDitemukan.setSize(new java.awt.Dimension(181, 130));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("DATA TIDAK");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("DITEMUKAN!!");

        btnOKTidakDitemukan.setText("OK");

        javax.swing.GroupLayout dialogTidakDitemukanLayout = new javax.swing.GroupLayout(dialogTidakDitemukan.getContentPane());
        dialogTidakDitemukan.getContentPane().setLayout(dialogTidakDitemukanLayout);
        dialogTidakDitemukanLayout.setHorizontalGroup(
            dialogTidakDitemukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogTidakDitemukanLayout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogTidakDitemukanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(50, 50, 50))
            .addGroup(dialogTidakDitemukanLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnOKTidakDitemukan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogTidakDitemukanLayout.setVerticalGroup(
            dialogTidakDitemukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogTidakDitemukanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(btnOKTidakDitemukan)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi TA");
        setResizable(false);

        txFieldGetIdMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldGetIdMahasiswaActionPerformed(evt);
            }
        });

        txFieldShowNIM.setEditable(false);
        txFieldShowNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNIMActionPerformed(evt);
            }
        });

        jLabel17.setText("ID Mahasiswa");

        jLabel23.setText("NIM");

        jLabel24.setText("Jumlah SKS");

        jLabel25.setText("Status KP");

        btnOKViewDataMahasiswa.setText("OK");
        btnOKViewDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKViewDataMahasiswaActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("LIHAT DATA MAHASISWA");

        txFieldShowJumlahSKS.setEditable(false);
        txFieldShowJumlahSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowJumlahSKSActionPerformed(evt);
            }
        });

        txFieldShowStatusKP.setEditable(false);
        txFieldShowStatusKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowStatusKPActionPerformed(evt);
            }
        });

        txFieldShowNamaMahasiswa.setEditable(false);
        txFieldShowNamaMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNamaMahasiswaActionPerformed(evt);
            }
        });

        jLabel27.setText("Nama");

        javax.swing.GroupLayout panelViewDataMahasiswaLayout = new javax.swing.GroupLayout(panelViewDataMahasiswa);
        panelViewDataMahasiswa.setLayout(panelViewDataMahasiswaLayout);
        panelViewDataMahasiswaLayout.setHorizontalGroup(
            panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelViewDataMahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(43, 43, 43)
                        .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFieldGetIdMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(txFieldShowNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldShowNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldShowJumlahSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldShowStatusKP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOKViewDataMahasiswa)
                .addGap(151, 151, 151))
        );
        panelViewDataMahasiswaLayout.setVerticalGroup(
            panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldGetIdMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txFieldShowNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txFieldShowJumlahSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowStatusKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(28, 28, 28)
                .addComponent(btnOKViewDataMahasiswa)
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Lihat Data Dosen");

        txFieldShowNamaDosen.setEditable(false);
        txFieldShowNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNamaDosenActionPerformed(evt);
            }
        });

        txFieldShowStatusDosen.setEditable(false);
        txFieldShowStatusDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowStatusDosenActionPerformed(evt);
            }
        });

        txFieldShowJumlahKelompokTA.setEditable(false);
        txFieldShowJumlahKelompokTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowJumlahKelompokTAActionPerformed(evt);
            }
        });

        btnOKViewDataDosen.setText("OK");
        btnOKViewDataDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKViewDataDosenActionPerformed(evt);
            }
        });

        jLabel18.setText("Pembimbing ke-");

        jLabel19.setText("Jumlah Kelompok TA");

        jLabel20.setText("NIP");

        jLabel21.setText("Nama");

        jLabel22.setText("ID Dosen");

        txFieldGetIdDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldGetIdDosenActionPerformed(evt);
            }
        });

        txFieldShowNIP.setEditable(false);
        txFieldShowNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldShowNIPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewDataDosenLayout = new javax.swing.GroupLayout(panelViewDataDosen);
        panelViewDataDosen.setLayout(panelViewDataDosenLayout);
        panelViewDataDosenLayout.setHorizontalGroup(
            panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel6))
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnOKViewDataDosen)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataDosenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txFieldGetIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataDosenLayout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txFieldShowJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataDosenLayout.createSequentialGroup()
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txFieldShowNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataDosenLayout.createSequentialGroup()
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txFieldShowNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewDataDosenLayout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txFieldShowStatusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        panelViewDataDosenLayout.setVerticalGroup(
            panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewDataDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldGetIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txFieldShowNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(txFieldShowStatusDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewDataDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldShowJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(btnOKViewDataDosen)
                .addContainerGap())
        );

        panelLoginDosen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("MENU LOGIN DOSEN");

        txFieldIdDosen.setText("ID Dosen");

        pswFieldDosen.setText("password");

        btnLoginDosen.setText("Login");

        javax.swing.GroupLayout panelLoginDosenLayout = new javax.swing.GroupLayout(panelLoginDosen);
        panelLoginDosen.setLayout(panelLoginDosenLayout);
        panelLoginDosenLayout.setHorizontalGroup(
            panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginDosenLayout.createSequentialGroup()
                .addGroup(panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginDosenLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldIdDosen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswFieldDosen, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelLoginDosenLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnLoginDosen)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelLoginDosenLayout.setVerticalGroup(
            panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswFieldDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginDosen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MENU LOGIN MAHASISWA");

        txFieldIdMahasiswa.setText("ID Mahasiswa");

        pswFieldMahasiswa.setText("password");

        btnLoginMahasiswa.setText("Login");

        javax.swing.GroupLayout panelLoginMahasiswaLayout = new javax.swing.GroupLayout(panelLoginMahasiswa);
        panelLoginMahasiswa.setLayout(panelLoginMahasiswaLayout);
        panelLoginMahasiswaLayout.setHorizontalGroup(
            panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                .addGroup(panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldIdMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswFieldMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnLoginMahasiswa)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelLoginMahasiswaLayout.setVerticalGroup(
            panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldIdMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswFieldMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginMahasiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txFieldNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNamaDosenActionPerformed(evt);
            }
        });

        txFieldNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNIPActionPerformed(evt);
            }
        });

        txFieldJumlahKelompokTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldJumlahKelompokTAActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        jLabel5.setText("NIP");

        jLabel7.setText("Jumlah Kelompok TA");

        btnCancelRegDosen.setText("Cancel");
        btnCancelRegDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegDosenActionPerformed(evt);
            }
        });

        btnSubmitRegDosen.setText("Submit");
        btnSubmitRegDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRegDosenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("REGISTRASI DOSEN");

        cmBoxStatusPembimbing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        jLabel16.setText("Pembimbing ke-");

        javax.swing.GroupLayout panelRegDosenLayout = new javax.swing.GroupLayout(panelRegDosen);
        panelRegDosen.setLayout(panelRegDosenLayout);
        panelRegDosenLayout.setHorizontalGroup(
            panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txFieldNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmBoxStatusPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txFieldJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnSubmitRegDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelRegDosen)
                .addGap(99, 99, 99))
            .addGroup(panelRegDosenLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegDosenLayout.setVerticalGroup(
            panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmBoxStatusPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelRegDosen)
                    .addComponent(btnSubmitRegDosen))
                .addGap(47, 47, 47))
        );

        txFieldNamaMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNamaMahasiswaActionPerformed(evt);
            }
        });

        txFieldNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNIMActionPerformed(evt);
            }
        });

        jLabel9.setText("Nama");

        jLabel10.setText("NIM");

        jLabel11.setText("Jumlah SKS");

        jLabel12.setText("Status KP");

        btnCancelRegMahasiswa.setText("Cancel");
        btnCancelRegMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegMahasiswaActionPerformed(evt);
            }
        });

        btnSubmitRegMahasiswa.setText("Submit");
        btnSubmitRegMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRegMahasiswaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("REGISTRASI MAHASISWA");

        cmBoxStatusKP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sudah", "belum" }));
        cmBoxStatusKP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmBoxStatusKP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBoxStatusKPActionPerformed(evt);
            }
        });

        txFieldJumlahSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldJumlahSKSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegMahasiswaLayout = new javax.swing.GroupLayout(panelRegMahasiswa);
        panelRegMahasiswa.setLayout(panelRegMahasiswaLayout);
        panelRegMahasiswaLayout.setHorizontalGroup(
            panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txFieldNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                        .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(72, 72, 72))
                            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmBoxStatusKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txFieldNIM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txFieldJumlahSKS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegMahasiswaLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnSubmitRegMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelRegMahasiswa)
                .addGap(99, 99, 99))
            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegMahasiswaLayout.setVerticalGroup(
            panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNamaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txFieldJumlahSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmBoxStatusKP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelRegMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelRegMahasiswa)
                    .addComponent(btnSubmitRegMahasiswa))
                .addGap(47, 47, 47))
        );

        menuFile.setText("File");

        menuBukaFile.setText("Buka file");
        menuFile.add(menuBukaFile);

        menuSimpanFile.setText("Simpan file");
        menuFile.add(menuSimpanFile);

        menuBar.add(menuFile);

        menuLogin.setText("Login");

        menuLoginDosen.setText("Login Dosen");
        menuLogin.add(menuLoginDosen);

        menuLoginMahasiswa.setText("Login Mahasiswa");
        menuLogin.add(menuLoginMahasiswa);

        menuBar.add(menuLogin);

        menuRegistrasi.setText("Registrasi");

        menuRegDosen.setText("Reg. Dosen");
        menuRegistrasi.add(menuRegDosen);

        menuRegMahasiswa.setText("Reg. Mahasiswa");
        menuRegistrasi.add(menuRegMahasiswa);

        menuBar.add(menuRegistrasi);

        menuView.setText("View");

        menuViewDataDosen.setText("Data Dosen");
        menuView.add(menuViewDataDosen);

        menuViewDataMahasiswa.setText("Data Mahasiswa");
        menuView.add(menuViewDataMahasiswa);

        menuBar.add(menuView);

        menuLogout.setText("Logout");
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelViewDataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelViewDataDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelViewDataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelViewDataDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelRegMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txFieldNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNamaDosenActionPerformed

    private void txFieldNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNIPActionPerformed

    private void txFieldJumlahKelompokTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldJumlahKelompokTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldJumlahKelompokTAActionPerformed

    private void btnCancelRegDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRegDosenActionPerformed

    private void btnSubmitRegDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRegDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitRegDosenActionPerformed

    private void btnSubmitRegMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRegMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitRegMahasiswaActionPerformed

    private void txFieldNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNIMActionPerformed

    private void txFieldNamaMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNamaMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNamaMahasiswaActionPerformed

    private void txFieldJumlahSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldJumlahSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldJumlahSKSActionPerformed

    private void btnOKBerhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKBerhasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOKBerhasilActionPerformed

    private void txFieldShowNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNamaDosenActionPerformed

    private void txFieldShowStatusDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowStatusDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowStatusDosenActionPerformed

    private void txFieldShowJumlahKelompokTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowJumlahKelompokTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowJumlahKelompokTAActionPerformed

    private void btnOKViewDataDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKViewDataDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOKViewDataDosenActionPerformed

    private void txFieldGetIdDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldGetIdDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldGetIdDosenActionPerformed

    private void txFieldShowNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNIPActionPerformed

    private void cmBoxStatusKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBoxStatusKPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmBoxStatusKPActionPerformed

    private void btnCancelRegMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRegMahasiswaActionPerformed

    private void txFieldGetIdMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldGetIdMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldGetIdMahasiswaActionPerformed

    private void txFieldShowNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNIMActionPerformed

    private void btnOKViewDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKViewDataMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOKViewDataMahasiswaActionPerformed

    private void txFieldShowJumlahSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowJumlahSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowJumlahSKSActionPerformed

    private void txFieldShowStatusKPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowStatusKPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowStatusKPActionPerformed

    private void txFieldShowNamaMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldShowNamaMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldShowNamaMahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //GETTER TEXT FIELD AND COMBO BOX
    public int getTxFieldIdDosen() {
        return Integer.parseInt(txFieldIdDosen.getText());
    }
    public String getPswFieldDosen() {
        return pswFieldDosen.getText();
    }
    public int getTxFieldIdMahasiswa() {
        return Integer.parseInt(txFieldIdMahasiswa.getText());
    }
    public String getPswFieldMahasiswa() {
        return pswFieldMahasiswa.getText();
    }
    public String getTxFieldNamaDosen() {
        return txFieldNamaDosen.getText();
    }
    public int getTxFieldJumlahSKS() {
        return Integer.parseInt(txFieldJumlahSKS.getText());
    }
    public long getTxFieldNIM() {
        return Long.parseLong(txFieldNIM.getText());
    }
    public String getTxFieldNamaMahasiswa() {
        return txFieldNamaMahasiswa.getText();
    } 
    public int getTxFieldJumlahKelompokTA() {
        return Integer.parseInt(txFieldJumlahKelompokTA.getText());
    }
    public long getTxFieldNIP() {
        return Long.parseLong(txFieldNIP.getText());
    }
    public int getCmBoxStatusPembimbing() {
        return cmBoxStatusPembimbing.getSelectedIndex()+1;
    }
    public boolean getCmBoxStatusKP() {
        if(cmBoxStatusKP.getSelectedIndex() == 0) {
            return true;
        }
        else {
            return false;
        }
    }
    public int getTxFieldGetIdDosen() {
        return Integer.parseInt(txFieldGetIdDosen.getText());
    }
    public int getTxFieldGetIdMahasiswa() {
        return Integer.parseInt(txFieldGetIdMahasiswa.getText());
    }
    
    
    //GETTER MENU AND BUTTON
    public Object getBtnOKSelamatDatang() {
        return btnOKSelamatDatang;
    }
    public Object getBtnOKBerhasil() {
        return btnOKBerhasil;
    }   
    public Object getBtnLoginDosen() {
        return btnLoginDosen;
    }
    public Object getBtnLoginMahasiswa() {
        return btnLoginMahasiswa;
    }
    public Object getMenuLoginDosen() {
        return menuLoginDosen;
    }
    public Object getMenuLoginMahasiswa() {
        return menuLoginMahasiswa;
    }
    public Object getBtnCancelRegMahasiswa() {
        return btnCancelRegMahasiswa;
    }
    public Object getBtnSubmitRegMahasiswa() {
        return btnSubmitRegMahasiswa;
    }
    public Object getBtnCancelRegDosen() {
        return btnCancelRegDosen;
    }
    public Object getBtnSubmitRegDosen() {
        return btnSubmitRegDosen;
    }
    public Object getBtnOKViewDataDosen() {
        return btnOKViewDataDosen;
    }
    public Object getBtnOKViewDataMahasiswa() {
        return btnOKViewDataMahasiswa;
    }
    public Object getBtnOKUserPswSalah() {
        return btnOKUserPswSalah;
    }
    public Object getBtnOKTidakDitemukan() {
        return btnOKTidakDitemukan;
    }  
    public Object getMenuBukaFile() {
        return menuBukaFile;
    }
    public Object getMenuSimpanFile() {
        return menuSimpanFile;
    }
    public Object getMenuRegDosen() {
        return menuRegDosen;
    }
    public Object getMenuRegMahasiswa() {
        return menuRegMahasiswa;
    }
    public Object getMenuViewDataDosen() {
        return menuViewDataDosen;
    }
    public Object getMenuViewDataMahasiswa() {
        return menuViewDataMahasiswa;
    }
    public Object getMenuLogout() {
        return menuLogout;
    }
    
    
    //GETTER PANEL AND DIALOG
    public JPanel getPanelLoginDosen() {
        return panelLoginDosen;
    }
    public JPanel getPanelLoginMahasiswa() {
        return panelLoginMahasiswa;
    }
    public JDialog getDialogSelamatDatang() {
        return dialogSelamatDatang;
    }
    public JDialog getDialogUserPswSalah() {
        return dialogUserPswSalah;
    }  
    public JPanel getPanelRegDosen() {
        return panelRegDosen;
    }
    public JPanel getPanelRegMahasiswa() {
        return panelRegMahasiswa;
    }
    public JDialog getDialogBerhasil() {
        return dialogRegistrasiBerhasil;
    }
    public JPanel getPanelViewDataDosen() {
        return panelViewDataDosen;
    }
    public JPanel getPanelViewDataMahasiswa() {
        return panelViewDataMahasiswa;
    }
    public JDialog getDialogTidakDitemukan() {
        return dialogTidakDitemukan;
    }
    
    
    //SETTER TEXT FIELD
    public void setTxFieldSelamatDatang(String nama) {
        txFieldSelamatDatang.setText(nama);
    }
    public void setTxFieldBerhasil(String id) {
        txFieldBerhasil.setText(id);
    }
    public void setTxFieldShowNamaDosen(String nama) {
        txFieldShowNamaDosen.setText(nama);
    }
    public void setTxFieldShowNIP(long nip) {
        txFieldShowNIP.setText(Long.toString(nip));
    }
    public void setTxFieldShowStatusDosen(int status) {
        txFieldShowStatusDosen.setText(Integer.toString(status));
    }
    public void setTxFieldShowJumlahKelompokTA(int jumlah) {
        txFieldShowJumlahKelompokTA.setText(Integer.toString(jumlah));
    }
    public void setTxFieldShowJumlahSKS(int jumlahSKS) {
        txFieldShowJumlahSKS.setText(Integer.toString(jumlahSKS));
    }
    public void setTxFieldShowNIM(long nim) {
        txFieldShowNIM.setText(Long.toString(nim));
    }
    public void setTxFieldShowNamaMahasiswa(String nama) {
        txFieldShowNamaMahasiswa.setText(nama);
    }
    public void setTxFieldShowStatusKP(boolean statusKP) {
        if(statusKP) {
            txFieldShowStatusKP.setText("Sudah");
        }
        else {
            txFieldShowStatusKP.setText("Belum");    
        }
    }
    
    
    
    public void addListener(ActionListener e) {
        menuViewDataDosen.addActionListener(e);
        menuViewDataMahasiswa.addActionListener(e);
        menuBukaFile.addActionListener(e);
        menuSimpanFile.addActionListener(e);
        menuLoginMahasiswa.addActionListener(e);
        menuLoginDosen.addActionListener(e);
        menuRegDosen.addActionListener(e);
        menuLogout.addActionListener(e);
        menuRegMahasiswa.addActionListener(e);
        
        btnLoginDosen.addActionListener(e);
        btnLoginMahasiswa.addActionListener(e);
        btnOKSelamatDatang.addActionListener(e);
        btnSubmitRegDosen.addActionListener(e);
        btnCancelRegDosen.addActionListener(e);
        btnCancelRegMahasiswa.addActionListener(e);
        btnSubmitRegMahasiswa.addActionListener(e);
        btnOKBerhasil.addActionListener(e);
        btnOKViewDataDosen.addActionListener(e);
        btnOKUserPswSalah.addActionListener(e);
        btnOKTidakDitemukan.addActionListener(e);
        
        cmBoxStatusPembimbing.addActionListener(e);
        btnOKViewDataMahasiswa.addActionListener(e);
        cmBoxStatusKP.addActionListener(e);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRegDosen;
    private javax.swing.JButton btnCancelRegMahasiswa;
    private javax.swing.JButton btnLoginDosen;
    private javax.swing.JButton btnLoginMahasiswa;
    private javax.swing.JButton btnOKBerhasil;
    private javax.swing.JButton btnOKSelamatDatang;
    private javax.swing.JButton btnOKTidakDitemukan;
    private javax.swing.JButton btnOKUserPswSalah;
    private javax.swing.JButton btnOKViewDataDosen;
    private javax.swing.JButton btnOKViewDataMahasiswa;
    private javax.swing.JButton btnSubmitRegDosen;
    private javax.swing.JButton btnSubmitRegMahasiswa;
    private javax.swing.JComboBox<String> cmBoxStatusKP;
    private javax.swing.JComboBox<String> cmBoxStatusPembimbing;
    private javax.swing.JDialog dialogRegistrasiBerhasil;
    private javax.swing.JDialog dialogSelamatDatang;
    private javax.swing.JDialog dialogTidakDitemukan;
    private javax.swing.JDialog dialogUserPswSalah;
    private javax.swing.JFrame frameOlahDataDosen;
    private javax.swing.JFrame frameOlahDataMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBukaFile;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenuItem menuLoginDosen;
    private javax.swing.JMenuItem menuLoginMahasiswa;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenuItem menuRegDosen;
    private javax.swing.JMenuItem menuRegMahasiswa;
    private javax.swing.JMenu menuRegistrasi;
    private javax.swing.JMenuItem menuSimpanFile;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem menuViewDataDosen;
    private javax.swing.JMenuItem menuViewDataMahasiswa;
    private javax.swing.JPanel panelLoginDosen;
    private javax.swing.JPanel panelLoginMahasiswa;
    private javax.swing.JPanel panelRegDosen;
    private javax.swing.JPanel panelRegMahasiswa;
    private javax.swing.JPanel panelViewDataDosen;
    private javax.swing.JPanel panelViewDataMahasiswa;
    private javax.swing.JPasswordField pswFieldDosen;
    private javax.swing.JPasswordField pswFieldMahasiswa;
    private javax.swing.JTextField txFieldBerhasil;
    private javax.swing.JTextField txFieldGetIdDosen;
    private javax.swing.JTextField txFieldGetIdMahasiswa;
    private javax.swing.JTextField txFieldIdDosen;
    private javax.swing.JTextField txFieldIdMahasiswa;
    private javax.swing.JTextField txFieldJumlahKelompokTA;
    private javax.swing.JTextField txFieldJumlahSKS;
    private javax.swing.JTextField txFieldNIM;
    private javax.swing.JTextField txFieldNIP;
    private javax.swing.JTextField txFieldNamaDosen;
    private javax.swing.JTextField txFieldNamaMahasiswa;
    private javax.swing.JTextField txFieldSelamatDatang;
    private javax.swing.JTextField txFieldShowJumlahKelompokTA;
    private javax.swing.JTextField txFieldShowJumlahSKS;
    private javax.swing.JTextField txFieldShowNIM;
    private javax.swing.JTextField txFieldShowNIP;
    private javax.swing.JTextField txFieldShowNamaDosen;
    private javax.swing.JTextField txFieldShowNamaMahasiswa;
    private javax.swing.JTextField txFieldShowStatusDosen;
    private javax.swing.JTextField txFieldShowStatusKP;
    // End of variables declaration//GEN-END:variables
}
