/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author agungrb
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSelamatDatang = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        txFieldSelamatDatang = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        panelRegDosen = new javax.swing.JPanel();
        txFieldNamaDosen = new javax.swing.JTextField();
        txFieldNIP = new javax.swing.JTextField();
        txFieldStatusPembimbing = new javax.swing.JTextField();
        txFieldJumlahKelompokTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCancelRegDosen = new javax.swing.JButton();
        btnSubmitRegDosen = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelLoginDosen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txFieldIdDosen = new javax.swing.JTextField();
        pswFieldDosen = new javax.swing.JPasswordField();
        btnLoginDosen = new javax.swing.JButton();
        panelLoginMahasiswa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txFieldIdMahasiswa = new javax.swing.JTextField();
        pswFieldMahasiswa = new javax.swing.JPasswordField();
        btnLoginMahasiswa = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuBukaFile = new javax.swing.JMenuItem();
        menuSimpanFile = new javax.swing.JMenuItem();
        menuLogin = new javax.swing.JMenu();
        menuLoginDosen = new javax.swing.JMenuItem();
        menuLoginMahasiswa = new javax.swing.JMenuItem();
        menuRegistrasi = new javax.swing.JMenu();
        menuRegDosen = new javax.swing.JMenuItem();
        menuRegMahasiswa = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuViewDataDosen = new javax.swing.JMenuItem();
        MenuViewDataMahasiswa = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenu();

        dialogSelamatDatang.setResizable(false);
        dialogSelamatDatang.setSize(new java.awt.Dimension(186, 130));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selamat Datang");

        txFieldSelamatDatang.setEditable(false);
        txFieldSelamatDatang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txFieldSelamatDatang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txFieldSelamatDatang.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnOK.setText("OK");

        javax.swing.GroupLayout dialogSelamatDatangLayout = new javax.swing.GroupLayout(dialogSelamatDatang.getContentPane());
        dialogSelamatDatang.getContentPane().setLayout(dialogSelamatDatangLayout);
        dialogSelamatDatangLayout.setHorizontalGroup(
            dialogSelamatDatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                .addGroup(dialogSelamatDatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnOK)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addComponent(txFieldSelamatDatang)
        );
        dialogSelamatDatangLayout.setVerticalGroup(
            dialogSelamatDatangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogSelamatDatangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldSelamatDatang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi TA");

        txFieldNamaDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNamaDosenActionPerformed(evt);
            }
        });

        txFieldNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldNIPActionPerformed(evt);
            }
        });

        txFieldStatusPembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldStatusPembimbingActionPerformed(evt);
            }
        });

        txFieldJumlahKelompokTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txFieldJumlahKelompokTAActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama");

        jLabel5.setText("NIP");

        jLabel6.setText("Status Pembimbing");

        jLabel7.setText("Jumlah Kelompok TA");

        btnCancelRegDosen.setText("Cancel");
        btnCancelRegDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegDosenActionPerformed(evt);
            }
        });

        btnSubmitRegDosen.setText("Submit");
        btnSubmitRegDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRegDosenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("REGISTRASI DOSEN");

        javax.swing.GroupLayout panelRegDosenLayout = new javax.swing.GroupLayout(panelRegDosen);
        panelRegDosen.setLayout(panelRegDosenLayout);
        panelRegDosenLayout.setHorizontalGroup(
            panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(txFieldNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txFieldStatusPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegDosenLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txFieldJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegDosenLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnSubmitRegDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelRegDosen)
                .addGap(99, 99, 99))
            .addGroup(panelRegDosenLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegDosenLayout.setVerticalGroup(
            panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNamaDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldNIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldStatusPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txFieldJumlahKelompokTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(panelRegDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelRegDosen)
                    .addComponent(btnSubmitRegDosen))
                .addGap(47, 47, 47))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("MENU LOGIN DOSEN");

        txFieldIdDosen.setText("ID Dosen");

        pswFieldDosen.setText("password");

        btnLoginDosen.setText("Login");

        javax.swing.GroupLayout panelLoginDosenLayout = new javax.swing.GroupLayout(panelLoginDosen);
        panelLoginDosen.setLayout(panelLoginDosenLayout);
        panelLoginDosenLayout.setHorizontalGroup(
            panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginDosenLayout.createSequentialGroup()
                .addGroup(panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginDosenLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldIdDosen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswFieldDosen, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelLoginDosenLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnLoginDosen)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelLoginDosenLayout.setVerticalGroup(
            panelLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginDosenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldIdDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswFieldDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginDosen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MENU LOGIN MAHASISWA");

        txFieldIdMahasiswa.setText("ID Mahasiswa");

        pswFieldMahasiswa.setText("password");

        btnLoginMahasiswa.setText("Login");

        javax.swing.GroupLayout panelLoginMahasiswaLayout = new javax.swing.GroupLayout(panelLoginMahasiswa);
        panelLoginMahasiswa.setLayout(panelLoginMahasiswaLayout);
        panelLoginMahasiswaLayout.setHorizontalGroup(
            panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                .addGroup(panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txFieldIdMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pswFieldMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnLoginMahasiswa)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelLoginMahasiswaLayout.setVerticalGroup(
            panelLoginMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginMahasiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txFieldIdMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pswFieldMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLoginMahasiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        menuBukaFile.setText("Buka file");
        menuFile.add(menuBukaFile);

        menuSimpanFile.setText("Simpan file");
        menuFile.add(menuSimpanFile);

        menuBar.add(menuFile);

        menuLogin.setText("Login");

        menuLoginDosen.setText("Login Dosen");
        menuLogin.add(menuLoginDosen);

        menuLoginMahasiswa.setText("Login Mahasiswa");
        menuLogin.add(menuLoginMahasiswa);

        menuBar.add(menuLogin);

        menuRegistrasi.setText("Registrasi");

        menuRegDosen.setText("Reg. Dosen");
        menuRegistrasi.add(menuRegDosen);

        menuRegMahasiswa.setText("Reg. Mahasiswa");
        menuRegistrasi.add(menuRegMahasiswa);

        menuBar.add(menuRegistrasi);

        menuView.setText("View");

        menuViewDataDosen.setText("Data Dosen");
        menuView.add(menuViewDataDosen);

        MenuViewDataMahasiswa.setText("Data Mahasiswa");
        menuView.add(MenuViewDataMahasiswa);

        menuBar.add(menuView);

        menuLogout.setText("Logout");
        menuBar.add(menuLogout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelLoginMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txFieldNamaDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNamaDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNamaDosenActionPerformed

    private void txFieldNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldNIPActionPerformed

    private void txFieldStatusPembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldStatusPembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldStatusPembimbingActionPerformed

    private void txFieldJumlahKelompokTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txFieldJumlahKelompokTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txFieldJumlahKelompokTAActionPerformed

    private void btnCancelRegDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelRegDosenActionPerformed

    private void btnSubmitRegDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRegDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitRegDosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public int getTxFieldIdDosen() {
        return Integer.parseInt(txFieldIdDosen.getText());
    }
    public String getPswFieldDosen() {
        return pswFieldDosen.getText();
    }
    public int getTxFieldIdMahasiswa() {
        return Integer.parseInt(txFieldIdMahasiswa.getText());
    }
    public String getPswFieldMahasiswa() {
        return pswFieldMahasiswa.getText();
    }
    public String getTxFieldNamaDosen() {
        return txFieldNamaDosen.getText();
    }

    public int getTxFieldJumlahKelompokTA() {
        return Integer.parseInt(txFieldJumlahKelompokTA.getText());
    }

    public long getTxFieldNIP() {
        return Long.parseLong(txFieldNIP.getText());
    }

    public int getTxFieldStatusPembimbing() {
        return Integer.parseInt(txFieldStatusPembimbing.getText());
    }
    
    
    public Object getBtnOK() {
        return btnOK;
    }
    public Object getBtnLoginDosen() {
        return btnLoginDosen;
    }
    public Object getBtnLoginMahasiswa() {
        return btnLoginMahasiswa;
    }
    public Object getMenuLoginDosen() {
        return menuLoginDosen;
    }
    public Object getMenuLoginMahasiswa() {
        return menuLoginMahasiswa;
    }
    public Object getMenuBukaFile() {
        return menuBukaFile;
    }
    public Object getMenuSimpanFile() {
        return menuSimpanFile;
    }
    public Object getMenuRegDosen() {
        return menuRegDosen;
    }

    public Object getBtnCancelRegDosen() {
        return btnCancelRegDosen;
    }

    public Object getBtnSubmitRegDosen() {
        return btnSubmitRegDosen;
    }
    
    
    public javax.swing.JPanel getPanelLoginDosen() {
        return panelLoginDosen;
    }
    public javax.swing.JPanel getPanelLoginMahasiswa() {
        return panelLoginMahasiswa;
    }
    public javax.swing.JDialog getDialogSelamatDatang() {
        return dialogSelamatDatang;
    }
    public javax.swing.JPanel getPanelRegDosen() {
        return panelRegDosen;
    }
    
    public void setTxFieldNama(String nama) {
        txFieldSelamatDatang.setText(nama);
    }
    
    public void addListener(ActionListener e) {
        btnLoginDosen.addActionListener(e);
        btnLoginMahasiswa.addActionListener(e);
        menuBukaFile.addActionListener(e);
        menuSimpanFile.addActionListener(e);
        menuLoginDosen.addActionListener(e);
        menuLoginMahasiswa.addActionListener(e);
        btnOK.addActionListener(e);
        menuRegDosen.addActionListener(e);
        btnSubmitRegDosen.addActionListener(e);
        btnCancelRegDosen.addActionListener(e);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuViewDataMahasiswa;
    private javax.swing.JButton btnCancelRegDosen;
    private javax.swing.JButton btnLoginDosen;
    private javax.swing.JButton btnLoginMahasiswa;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSubmitRegDosen;
    private javax.swing.JDialog dialogSelamatDatang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBukaFile;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenuItem menuLoginDosen;
    private javax.swing.JMenuItem menuLoginMahasiswa;
    private javax.swing.JMenu menuLogout;
    private javax.swing.JMenuItem menuRegDosen;
    private javax.swing.JMenuItem menuRegMahasiswa;
    private javax.swing.JMenu menuRegistrasi;
    private javax.swing.JMenuItem menuSimpanFile;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenuItem menuViewDataDosen;
    private javax.swing.JPanel panelLoginDosen;
    private javax.swing.JPanel panelLoginMahasiswa;
    private javax.swing.JPanel panelRegDosen;
    private javax.swing.JPasswordField pswFieldDosen;
    private javax.swing.JPasswordField pswFieldMahasiswa;
    private javax.swing.JTextField txFieldIdDosen;
    private javax.swing.JTextField txFieldIdMahasiswa;
    private javax.swing.JTextField txFieldJumlahKelompokTA;
    private javax.swing.JTextField txFieldNIP;
    private javax.swing.JTextField txFieldNamaDosen;
    private javax.swing.JTextField txFieldSelamatDatang;
    private javax.swing.JTextField txFieldStatusPembimbing;
    // End of variables declaration//GEN-END:variables
}
